"""
main.py
-------
Command-line interface for the AI Student Support Assistant.

  - Answers are generated by a local Ollama model if one is running,
    otherwise the app falls back to an offline template answer -- either
    way it always works.
  - Conversation history and student profile are persisted to SQLite
    (assistant.db), keyed by a session id, so they survive between runs.

Usage:
    python main.py                    # prompts for a session id
    python main.py --session amit123  # skip the prompt

Commands inside the chat:
    /profile   - show what the agent remembers about you
    /history   - show this session's full persisted conversation history
    /stats     - show knowledge-base stats
    /reset     - clear this session's conversation + profile memory
    /exit      - quit
"""

import argparse
import json
import urllib.request

from agent import StudentSupportAgent
from llm import llm_client


BANNER = """
============================================================
  AI STUDENT SUPPORT ASSISTANT   (RAG + Tools + Memory)
  Local model: Ollama   |   History: SQLite
============================================================
Ask about regulations, syllabus, exams, fees, or notices.
Commands: /profile  /history  /stats  /reset  /exit
------------------------------------------------------------
"""


def check_ollama() -> str:
    """Ping Ollama and report status. Purely informational -- the app works either way."""
    try:
        req = urllib.request.Request(f"{llm_client.OLLAMA_HOST}/api/tags")
        with urllib.request.urlopen(req, timeout=2) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            names = [m["name"] for m in data.get("models", [])]
            if llm_client.OLLAMA_MODEL in names:
                return f"[ok] Connected to Ollama -- using model '{llm_client.OLLAMA_MODEL}'."
            elif names:
                return (f"[!] Connected to Ollama, but '{llm_client.OLLAMA_MODEL}' isn't pulled yet.\n"
                        f"    Available models: {', '.join(names)}\n"
                        f"    Run: ollama pull {llm_client.OLLAMA_MODEL}\n"
                        f"    Using offline answers until then.")
            else:
                return (f"[!] Connected to Ollama, but no models are pulled yet.\n"
                        f"    Run: ollama pull {llm_client.OLLAMA_MODEL}\n"
                        f"    Using offline answers until then.")
    except Exception:
        return (f"[offline] Ollama not detected at {llm_client.OLLAMA_HOST}.\n"
                f"    Install it from https://ollama.com, run `ollama serve`, then "
                f"`ollama pull {llm_client.OLLAMA_MODEL}` for local AI answers.\n"
                f"    Running in offline mode for now -- the app still works.")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--session", help="Session id (e.g. your roll number). Determines which saved history loads.")
    args = parser.parse_args()

    session_id = args.session
    if not session_id:
        session_id = input("Session id (e.g. your roll number, Enter for 'default'): ").strip() or "default"

    print(BANNER)
    print(check_ollama())
    print()

    agent = StudentSupportAgent(session_id=session_id)
    if agent.memory.history:
        print(f"(Resuming session '{session_id}' -- {len(agent.memory.history)} past turns loaded from SQLite.)\n")

    while True:
        try:
            question = input("You: ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nGoodbye!")
            break

        if not question:
            continue
        if question.lower() in ("/exit", "quit", "exit"):
            print("Goodbye!")
            break
        if question.lower() == "/profile":
            print(f"Assistant (memory): {agent.memory.profile_text()}\n")
            continue
        if question.lower() == "/history":
            if not agent.memory.history:
                print("No history yet for this session.\n")
            for t in agent.memory.history:
                print(f"  [{t.timestamp}] {t.role}: {t.content[:120]}")
            print()
            continue
        if question.lower() == "/stats":
            print(f"Assistant (kb stats): {agent.retriever.stats()}\n")
            continue
        if question.lower() == "/reset":
            agent.memory.reset()
            print("Assistant: Memory cleared (SQLite history for this session deleted).\n")
            continue

        answer = agent.handle(question)
        print(f"\nAssistant: {answer}\n")


if __name__ == "__main__":
    main()
